version: '2'
services:
  web7:
    build: ../nginx
    volumes_from:
      - container:vbase
    ports:
      - 80:80
      - 443:443
    links:
      - phpfpm
      - composer
      - mysql
      - mongodb
      - memcached
      - elasticsearch
  phpfpm:
    build: ../php7-fpm
    volumes_from:
      - container:vbase
  composer:
    image: composer:1.3
    volumes_from:
      - container:vbase
  mysql:
    image: pluie/alpine-mysql:latest
    volumes_from:
      - container:vbase
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=root
  mongodb:
    image: ellerbrock/alpine-mongodb:latest
  memcached:
    image: memcached:1.4-alpine
  elasticsearch:
    image: elasticsearch:5-alpine
