version: '2'
services:
  web7:
    build: ../images/nginx/ready/php-fpm
    volumes_from:
      - container:vbase
    ports:
      - 80:80
      - 443:443
    links:
      - phpfpm
      - composer
      - mysql
      - mongodb
      - memcached
      - elasticsearch
  phpfpm:
    build: ../images/php/7.1/fpm/xdebug
    volumes_from:
      - container:vbase
    environment:
      - XDEBUG_CONFIG="remote_host=172.21.0.1 remote_autostart=1"
  composer:
    image: composer:1.3
    volumes_from:
      - container:vbase
  mysql:
    image: pluie/alpine-mysql:latest
    volumes_from:
      - container:vbase
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=web7
      - MYSQL_USER=web7
      - MYSQL_PASSWORD=web7pass
  mongodb:
    image: ellerbrock/alpine-mongodb:latest
  memcached:
    image: memcached:1.4-alpine
  elasticsearch:
    image: elasticsearch:5-alpine
